Bubble sort
kazumaki/bubble-sort pull request #1
Opened 2019-10-22 21:03 UTC by kazumaki

2019-10-23 06:41 UTC, wathigo requested changes
### Hi @kazumaki  and @adaorachi  :wave:
Great work on the bubble sort algorithm!
The `bubble_sort_by` method works well but we have a problem in the `bubble_sort` method.
Let's fix all the linter errors. 
See the comment :point_down:  

**After implementing the changes, submit another request for review.**

_Happy Coding :computer:  
Reviewed by: **Simon Wathigo**_

2019-10-23 06:41 UTC, wathigo commented on bubble_sort.rb
> +        carry = arrToSort[j + 1]
**[REQUIRED]**  `arrToSort` variable is not defined. After changing it to `arr` the code passes the sample test cases. Let's fix this

2019-10-23 18:26 UTC, samgaco requested changes
Hi @kazumaki and @adaorachi :high_brightness: 

Just one thing left to change before proceeding. 

- [ ]  If no block is given bubble_sort_by should raise and error

fix that and submit back for another code review.

Regards!

----------------------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-23 18:26 UTC, samgaco commented on bubble_sort.rb
> +    (1..arr.length - (i + 1)).each do |j|
- [ ] If no block is given **bubble_sort_by** should raise and error

2019-10-24 17:19 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: . However the project is not approved yet :red_circle: . check :arrow_down: 

- According to the Git Flow guidelines:
  - Create a development branch, set it as the default branch.
  - Set the target branch of this pull request (i.e the branch in which you want to merge) to be development instead of master.

### That's it :relaxed: . When finished, kindly resubmit another code review request :pray: 

**Ahmed Mahfoudh**

2019-10-24 20:49 UTC, stratospherique approved these changes
### Congrats :tada: Your project is approved :heavy_check_mark: And you may merge to master :+1: :+1: 

Keep up the good work :muscle: 
**Ahmed Mahfoudh**

2019-10-24 21:04 UTC, merged